SCHEMA_NAME = "shopping_alert"
TABLE_PLATFORMS_NAME = "platforms"
TABLE_ITEMS_NAME = "items"
TABLE_SPECS_NAME = "specs"
TABLE_STATUS_NAME = "status"

CREATE_SCHEMA = f"CREATE SCHEMA IF NOT EXISTS {SCHEMA_NAME};"

CREATE_TABLE_PLATFORMS = f"""
CREATE TABLE IF NOT EXISTS {SCHEMA_NAME}.{TABLE_PLATFORMS_NAME} (
    platform_id SERIAL PRIMARY KEY,
    platform TEXT NOT NULL UNIQUE
);
"""

CREATE_TABLE_ITEMS = f"""
CREATE TABLE IF NOT EXISTS {SCHEMA_NAME}.{TABLE_ITEMS_NAME} (
    platform_id INTEGER NOT NULL,
    item_id TEXT NOT NULL,
    name TEXT NOT NULL,
    brand TEXT NOT NULL,
    currency TEXT NOT NULL,
    url TEXT NOT NULL
);
"""

CREATE_TABLE_SPECS = f"""
CREATE TABLE IF NOT EXISTS {SCHEMA_NAME}.{TABLE_SPECS_NAME} (
    specs_id SERIAL PRIMARY KEY,
    platform_id INTEGER NOT NULL,
    item_id TEXT NOT NULL,
    color TEXT NOT NULL,
    size TEXT NOT NULL
);
"""

CREATE_TABLE_STATUS = f"""
CREATE TABLE IF NOT EXISTS {SCHEMA_NAME}.{TABLE_STATUS_NAME} (
    status_id SERIAL PRIMARY KEY,
    specs_id INTEGER NOT NULL,
    original_price DOUBLE PRECISION,
    current_price DOUBLE PRECISION NOT NULL,
    inventory INTEGER,
    in_stock BOOLEAN NOT NULL,
    asof TIMESTAMP NOT NULL
);
"""

INITIALIZE_DB = f"""
{CREATE_SCHEMA}
{CREATE_TABLE_PLATFORMS}
{CREATE_TABLE_ITEMS}
{CREATE_TABLE_SPECS}
{CREATE_TABLE_STATUS}
"""

INSERT_PLATFORMS = f"""
INSERT INTO {SCHEMA_NAME}.{TABLE_PLATFORMS_NAME} (platform) VALUES (%(platform)s);
"""

QUERY_PLATFORMS = f"SELECT platform_id, platform FROM {SCHEMA_NAME}.{TABLE_PLATFORMS_NAME};"
